packages:
  - 'apps/*'

allowBuilds:
  sharp: true

# sdk-sync:start
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@tileflow/capture@0.1.0-alpha.17'
  - '@tileflow/cli@0.1.0-alpha.19'
  - '@tileflow/core@0.1.0-alpha.20'
  - '@tileflow/dev@0.1.0-alpha.18'
  - '@tileflow/next@0.1.0-alpha.17'
  - '@tileflow/react@0.1.0-alpha.19'
  - '@tileflow/static@0.1.0-alpha.17'
  - '@tileflow/vite@0.1.0-alpha.17'
# sdk-sync:end
